/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstalledRouteImport } from './routes/installed'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as RunRouteImport } from './routes/run'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ToolsToolIdRouteImport } from './routes/tools.$toolId'
import { Route as ApiV1CatalogRouteImport } from './routes/api/v1/catalog'
import { Route as ApiV1X402RouteImport } from './routes/api/v1/x402'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalledRoute = InstalledRouteImport.update({
  id: '/installed',
  path: '/installed',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsToolIdRoute = ToolsToolIdRouteImport.update({
  id: '/tools/$toolId',
  path: '/tools/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CatalogRoute = ApiV1CatalogRouteImport.update({
  id: '/api/v1/catalog',
  path: '/api/v1/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1X402Route = ApiV1X402RouteImport.update({
  id: '/api/v1/x402',
  path: '/api/v1/x402',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/installed': typeof InstalledRoute
  '/protocol': typeof ProtocolRoute
  '/run': typeof RunRoute
  '/wallet': typeof WalletRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/api/v1/catalog': typeof ApiV1CatalogRoute
  '/api/v1/x402': typeof ApiV1X402Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/installed': typeof InstalledRoute
  '/protocol': typeof ProtocolRoute
  '/run': typeof RunRoute
  '/wallet': typeof WalletRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/api/v1/catalog': typeof ApiV1CatalogRoute
  '/api/v1/x402': typeof ApiV1X402Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/installed': typeof InstalledRoute
  '/protocol': typeof ProtocolRoute
  '/run': typeof RunRoute
  '/wallet': typeof WalletRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/api/v1/catalog': typeof ApiV1CatalogRoute
  '/api/v1/x402': typeof ApiV1X402Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/installed'
    | '/protocol'
    | '/run'
    | '/wallet'
    | '/tools/$toolId'
    | '/api/v1/catalog'
    | '/api/v1/x402'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/installed'
    | '/protocol'
    | '/run'
    | '/wallet'
    | '/tools/$toolId'
    | '/api/v1/catalog'
    | '/api/v1/x402'
  id:
    | '__root__'
    | '/'
    | '/installed'
    | '/protocol'
    | '/run'
    | '/wallet'
    | '/tools/$toolId'
    | '/api/v1/catalog'
    | '/api/v1/x402'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstalledRoute: typeof InstalledRoute
  ProtocolRoute: typeof ProtocolRoute
  RunRoute: typeof RunRoute
  WalletRoute: typeof WalletRoute
  ToolsToolIdRoute: typeof ToolsToolIdRoute
  ApiV1CatalogRoute: typeof ApiV1CatalogRoute
  ApiV1X402Route: typeof ApiV1X402Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installed': {
      id: '/installed'
      path: '/installed'
      fullPath: '/installed'
      preLoaderRoute: typeof InstalledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolId': {
      id: '/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof ToolsToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/catalog': {
      id: '/api/v1/catalog'
      path: '/api/v1/catalog'
      fullPath: '/api/v1/catalog'
      preLoaderRoute: typeof ApiV1CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/x402': {
      id: '/api/v1/x402'
      path: '/api/v1/x402'
      fullPath: '/api/v1/x402'
      preLoaderRoute: typeof ApiV1X402RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstalledRoute: InstalledRoute,
  ProtocolRoute: ProtocolRoute,
  RunRoute: RunRoute,
  WalletRoute: WalletRoute,
  ToolsToolIdRoute: ToolsToolIdRoute,
  ApiV1CatalogRoute: ApiV1CatalogRoute,
  ApiV1X402Route: ApiV1X402Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
